# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

vectorProcess <- function(line, L, p, b, permFileName) {
    .Call('RBBitMinWise_vectorProcess', PACKAGE = 'RBBitMinWise', line, L, p, b, permFileName)
}

bBitCompress <- function(b, L, p, k, inFileName, permFileName, outFileName) {
    invisible(.Call('RBBitMinWise_bBitCompress', PACKAGE = 'RBBitMinWise', b, L, p, k, inFileName, permFileName, outFileName))
}

