// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// vectorProcess
Row vectorProcess(string line, const int L, const int p, const int b, const string permFileName);
RcppExport SEXP RBBitMinWise_vectorProcess(SEXP lineSEXP, SEXP LSEXP, SEXP pSEXP, SEXP bSEXP, SEXP permFileNameSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< string >::type line(lineSEXP);
    Rcpp::traits::input_parameter< const int >::type L(LSEXP);
    Rcpp::traits::input_parameter< const int >::type p(pSEXP);
    Rcpp::traits::input_parameter< const int >::type b(bSEXP);
    Rcpp::traits::input_parameter< const string >::type permFileName(permFileNameSEXP);
    __result = Rcpp::wrap(vectorProcess(line, L, p, b, permFileName));
    return __result;
END_RCPP
}
// bBitCompress
void bBitCompress(const int b, const int L, const int p, const int k, const string inFileName, const string permFileName, const string outFileName);
RcppExport SEXP RBBitMinWise_bBitCompress(SEXP bSEXP, SEXP LSEXP, SEXP pSEXP, SEXP kSEXP, SEXP inFileNameSEXP, SEXP permFileNameSEXP, SEXP outFileNameSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const int >::type b(bSEXP);
    Rcpp::traits::input_parameter< const int >::type L(LSEXP);
    Rcpp::traits::input_parameter< const int >::type p(pSEXP);
    Rcpp::traits::input_parameter< const int >::type k(kSEXP);
    Rcpp::traits::input_parameter< const string >::type inFileName(inFileNameSEXP);
    Rcpp::traits::input_parameter< const string >::type permFileName(permFileNameSEXP);
    Rcpp::traits::input_parameter< const string >::type outFileName(outFileNameSEXP);
    bBitCompress(b, L, p, k, inFileName, permFileName, outFileName);
    return R_NilValue;
END_RCPP
}
